CREATE DATABASE IF NOT EXISTS cims_users;
CREATE DATABASE IF NOT EXISTS cims_products;
CREATE DATABASE IF NOT EXISTS cims_inventory;
CREATE DATABASE IF NOT EXISTS cims_shopify;
CREATE DATABASE IF NOT EXISTS cims_marketplace;
CREATE DATABASE IF NOT EXISTS cims_audit;
CREATE DATABASE IF NOT EXISTS cims_orders;
CREATE DATABASE IF NOT EXISTS cims_notifications;
